# This is the name of the workflow
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Running Lint Check
        run: ./gradlew lintDebug

      - name: Uploading the HTML Report Artifact
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html